function roleToCaa(role){return role==='Student'?'Dual':role==='Co-pilot'?'Co-pilot':role==='PIC/US'?'':'PIC'}
function caaColumnIndex(engine,timeType,isNight){if(engine==='single'){if(timeType==='Dual')return isNight?2:0;if(timeType==='PIC')return isNight?3:1;return -1}const base=isNight?8:4;return base+({'Dual':0,'PIC':1,'Co-pilot':2,'Command practice':3}[timeType]??-99)}
function caaColumnsFor(f){const a=Array(17).fill(0),engine=f.engineClass||'single',tt=f.caaTimeType||roleToCaa(f.function);if(num(f.day)>0){const i=caaColumnIndex(engine,tt,false);if(i>=0)a[i]+=num(f.day)}if(num(f.night)>0){const i=caaColumnIndex(engine,tt,true);if(i>=0)a[i]+=num(f.night)}a[12]=num(f.actualInst);a[13]=num(f.simInst);a[14]=num(f.groundInst);a[15]=num(f.other16);a[16]=num(f.other17);return a}
function detailsFor(f){return String(f.details||f.detailsRaw||'').trim()}
function activeFlights(){return db.flights.filter(f=>!f.deleted)}
function pendingFlights(){return activeFlights().filter(f=>f.syncStatus!=='synced')}
function switchTab(name){document.querySelectorAll('.panel').forEach(p=>p.classList.toggle('active',p.id===name));document.querySelectorAll('.navbtn').forEach(b=>b.classList.toggle('on',b.dataset.go===name));window.scrollTo({top:0,behavior:'instant'});if(name==='add'&&!$('date').value)$('date').value=today();if(name==='sync')renderSync()}
document.addEventListener('click',e=>{const b=e.target.closest('[data-go]');if(b)switchTab(b.dataset.go)});$('fab').onclick=()=>switchTab('add');
let functionValue='PIC',dayNightValue='day',saveNextRequested=false;
function setSeg(root,val){[...root.querySelectorAll('button')].forEach(b=>b.classList.toggle('on',b.dataset.v===val))}
$('functionSeg').onclick=e=>{const b=e.target.closest('button[data-v]');if(!b)return;functionValue=b.dataset.v;setSeg($('functionSeg'),functionValue);const tt=roleToCaa(functionValue);$('caaTimeType').value=tt||'';$('pilotInCommand').value=functionValue==='PIC'?(db.settings.defaultPic||'Self'):'';$('coPilotStudent').value=['Student','Co-pilot','PIC/US'].includes(functionValue)?'Self':''};
$('dayNightSeg').onclick=e=>{const b=e.target.closest('button[data-v]');if(!b)return;const old=dayNightValue;dayNightValue=b.dataset.v;setSeg($('dayNightSeg'),dayNightValue);$('splitFields').classList.toggle('hidden',dayNightValue!=='split');if(old!==dayNightValue){if(dayNightValue==='night'){if(+$('takeoffsDay').value===1&&+$('landingsDay').value===1&&+$('takeoffsNight').value===0&&+$('landingsNight').value===0){$('takeoffsDay').value=0;$('landingsDay').value=0;$('takeoffsNight').value=1;$('landingsNight').value=1}}else if(dayNightValue==='day'){if(+$('takeoffsNight').value===1&&+$('landingsNight').value===1&&+$('takeoffsDay').value===0&&+$('landingsDay').value===0){$('takeoffsNight').value=0;$('landingsNight').value=0;$('takeoffsDay').value=1;$('landingsDay').value=1}}}}
function clearForm(keepDate=false){$('flightForm').reset();$('editId').value='';$('entryTitle').textContent='Add flight';functionValue='PIC';dayNightValue='day';setSeg($('functionSeg'),'PIC');setSeg($('dayNightSeg'),'day');$('splitFields').classList.add('hidden');$('date').value=keepDate?($('date').value||today()):today();$('takeoffsDay').value=1;$('landingsDay').value=1;$('takeoffsNight').value=0;$('landingsNight').value=0;$('engineClass').value='single';$('caaTimeType').value='PIC';$('pilotInCommand').value=db.settings.defaultPic||'Self';$('formError').classList.add('hidden')}
