function renderQueue(){const fs=activeFlights().slice().sort((a,b)=>b.createdAt-a.createdAt),p=pendingFlights().length;$('queueSummary').textContent=`${fs.length} phone entr${fs.length===1?'y':'ies'} · ${p} waiting for Excel`;$('queueFlights').innerHTML=fs.map(flightCard).join('')||'<div class="muted" style="padding:14px 0">No phone entries yet.</div>'}
function renderSettings(){const s=db.settings;$('pilotName').value=s.pilotName||'';$('secondName').value=s.secondName||'';$('clientNo').value=s.clientNo||'';$('defaultPic').value=s.defaultPic||'Self';$('col16Label').value=s.other16Label||'AS FLIGHT INSTRUCTOR';$('col17Label').value=s.other17Label||'IFR CROSS COUNTRY';$('aircraftList').innerHTML=(s.aircraft||[]).map((a,i)=>`<div class="item row"><div><strong>${esc(a.type||'—')}</strong> ${esc(a.reg||'')}<div class="hint">${a.engineClass==='multi'?'Multi-engine':'Single-engine'}</div></div><div class="spacer"></div><button class="danger small" onclick="removeAircraft(${i})">Remove</button></div>`).join('')||'<div class="muted">No aircraft shortcuts.</div>';$('detailsList').innerHTML=(s.commonDetails||[]).map((d,i)=>`<div class="item row"><span>${esc(d)}</span><div class="spacer"></div><button class="danger small" onclick="removeDetail(${i})">Remove</button></div>`).join('')||'<div class="muted">No Details shortcuts.</div>';const full=[s.pilotName,s.secondName].filter(Boolean).join(' ').trim();$('headerPilot').textContent=full||'Pilot';$('headerClient').textContent=s.clientNo?'CAA '+s.clientNo:'CAA —';$('other16Label').textContent=(s.other16Label||'CAA column 16')+' (col 16)';$('other17Label').textContent=(s.other17Label||'CAA column 17')+' (col 17)'}
for(const id of ['pilotName','secondName','clientNo','defaultPic','col16Label','col17Label'])$(id).onchange=()=>{db.settings.pilotName=$('pilotName').value.trim();db.settings.secondName=$('secondName').value.trim();db.settings.clientNo=$('clientNo').value.trim();db.settings.defaultPic=$('defaultPic').value.trim()||'Self';db.settings.other16Label=$('col16Label').value.trim()||'AS FLIGHT INSTRUCTOR';db.settings.other17Label=$('col17Label').value.trim()||'IFR CROSS COUNTRY';save()};
$('addAircraft').onclick=()=>{const type=$('newAircraftType').value.trim().toUpperCase(),reg=normaliseReg($('newAircraftReg').value);if(!type)return;db.settings.aircraft.push({type,reg,engineClass:$('newAircraftEngine').value});$('newAircraftType').value='';$('newAircraftReg').value='';save()};window.removeAircraft=i=>{db.settings.aircraft.splice(i,1);save()};$('addDetails').onclick=()=>{const d=$('newDetails').value.trim();if(!d)return;if(!(db.settings.commonDetails||[]).includes(d))db.settings.commonDetails.push(d);$('newDetails').value='';save()};window.removeDetail=i=>{db.settings.commonDetails.splice(i,1);save()};
function renderSync(){const p=pendingFlights();if(prepared){$('syncStatus').className='notice good';$('syncStatus').innerHTML=`Updated workbook prepared for <strong>${esc(prepared.name)}</strong>. Save it back to iCloud Drive, then confirm below.`;$('preparedBox').classList.remove('hidden')}else{$('syncStatus').className='notice '+(p.length?'info':'good');$('syncStatus').innerHTML=p.length?`<strong>${p.length}</strong> phone entr${p.length===1?'y':'ies'} waiting to be written to Excel.${db.settings.lastExcelName?`<br>Last workbook: ${esc(db.settings.lastExcelName)}`:''}`:'All phone entries are confirmed as written to Excel.';$('preparedBox').classList.add('hidden')}$('chooseExcel').disabled=!p.length||!!prepared}
function renderAll(){renderSettings();renderQuick();renderHome();renderQueue();renderSync()}

// --- XLSX reader/writer for the user's CAANZ V4.03 workbook ---
function u16(d,o){return d.getUint16(o,true)}function u32(d,o){return d.getUint32(o,true)}function xmlText(bytes){return new TextDecoder('utf-8').decode(bytes)}function parseXml(bytes){const d=new DOMParser().parseFromString(xmlText(bytes),'application/xml');if(d.getElementsByTagName('parsererror').length)throw Error('Excel XML could not be parsed.');return d}
